version: '3.8'

services:
  frontend:
    image: htx-frontend:latest
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: htx-backend:latest
    build:
      context: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    depends_on:
      - db
    networks:
      - app-network   

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./server/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
